config/routes.rb
Rails.application.routes.draw do
  root "doctors#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :patients, only: [:index, :show, :new, :create]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doctor.rb
class Doctor < User
  has_many :patients
  validates :email, presence: true
  validates :password, presence: true
  validates :specialization, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/patient.rb
class Patient < User
  belongs_to :doctor
  validates :email, presence: true,format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :disease, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :gender, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @doctor = Doctor.find(current_user.id)
    @total = @doctor.patients.count
    @patients = @doctor.patients
    @patients = @patients.where('first_name = ?', params[:search]) if params[:search].present?
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create
    @doctor = Doctor.find(current_user.id)
    @patient = @doctor.patients.new(patient_params)
    if @patient.save
      redirect_to patient_path(@patient), status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :email, :age, :disease, :gender, :phone_number, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/index.html.erb
<br>
<H2>Welcome <%= current_user.first_name %> <%= current_user.last_name %> in Patient Doctor App</H2>
<H2><%= current_user.first_name %> <%= current_user.last_name %> is a <%= current_user.specialization %></H2>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Patient Doc ", root_url, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li>
          <%= link_to "LogOut", destroy_user_session_path, data: {
            "turbo-method": :delete
          } ,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Add Patient", new_patient_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "See Patient", patients_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Go to Admin Dashboard", new_admin_user_session_path, class: "nav-link" %>
      </li>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PatDoc</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render "layouts/navigation" %>
<%= yield %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

app/views/patients/_error_msg.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <div class="panel-title">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this <%= obj.class %> for being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                  <li>
                    <%= msg %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/patients/index.html.erb
<center><h1>Patient List</h1></center>
<br>
<center>
  <h3>
    The Total Patient under the Doctor <b><%= current_user.first_name %>'s</b> are <b></b><%= @total %>
  </h3>
</center>
<div style="width: 20rem;">
  <%= form_tag patients_path, :method => "get" do %>
    <%= label_tag(:search, "What Patient you want to Search") %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag("Search") %>
  <% end %>
</div>
<br>
<%= link_to 'get me back', root_url, class: "btn btn-sm border border-dark rounded-sm" %>
<i class="bi bi-arrow-return-left"></i>
<br>
<table class="table">
  <thead>
  <tr>
    <th scope="col">Patient First Name</th>
    <th scope="col">Patient Last Name</th>
    <th scope="col">Disease</th>
    <th scope="col">Age</th>
  </tr>
  </thead>
  <tbody>
  <% @patients.each do |f| %>
    <% if f.doctor_id == current_user.id %>
      <tr>
        <td>
          <%= link_to f.first_name, patient_path(f) %>
        </td>
        <td>
          <%= link_to f.last_name, patient_path(f) %>
        </td>
        <td>
          <%= f.disease %>
        </td>
        <td>
          <%= f.age %>
        </td>
      </tr>
    <% end %>

  <% end %>
  </tbody>
</table>

app/views/patients/new.html.erb
<center>
  <h1>Add the new Patient</h1>
</center>
<%= render "patients/error_msg", obj: @patient %>
<%= form_with model: @patient do |form| %>
  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>
  <p>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </p>
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :age %><br>
    <%= form.text_field :age %>
  </p>
  <p>
    <%= form.label :disease %><br>
    <%= form.text_field :disease %>
  </p>
  <p>
    <%= form.label :gender %><br>
    <%= form.text_field :gender %>
  </p>
  <p>
    <%= form.label :phone_number %><br>
    <%= form.text_field :phone_number %>
  </p>
  <p>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </p>
  <br>
  <%= form.submit %>
  </p>
<% end %>

app/views/patients/show.html.erb
<center>
  <h1>Patient Details</h1>
</center>
<br>
<center>
  <%= link_to 'get me back', patients_path, class: "btn btn-sm border border-dark rounded-sm" %>
  <br>
  <div class="card" style="width: 30rem;">
    <div class="card-header">
      Details
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item font_style"><%= @patient.first_name %></li>
      <li class="list-group-item font_style"><%= @patient.last_name %></li>
      <li class="list-group-item font_style"><%= @patient.disease %></li>
      <li class="list-group-item font_style"><%= @patient.age %></li>
      <li class="list-group-item font_style"><%= @patient.gender %></li>
      <li class="list-group-item font_style"><%= @patient.phone_number %></li>
      <li class="list-group-item font_style"><%= @patient.address %></li>
    </ul>
  </div>
  <br>
</center>